/* lab_featurizer_check.mjs — node-side half of the client-featurizer parity
 * test (test_lab_featurizer_parity.py).
 *
 * Usage: node lab_featurizer_check.mjs <fixture.json> <lab_features_module>
 *
 * The fixture is generated by the pytest half from the SERVER featurizer
 * (shrimp.features.build_features / showcase.lab.build_free_position); this
 * script recomputes every position with the client mirror (lab_features.js)
 * and fails on any support-order or feature-value divergence (tolerance 1e-6).
 * The module path argument points at a copy of web/learn/lab_features.js with
 * an .mjs suffix (the repo has no package.json, so node needs the extension
 * to treat it as an ES module).
 */

import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const [fixturePath, modulePath] = process.argv.slice(2);
if (!fixturePath || !modulePath) {
  console.error("usage: node lab_featurizer_check.mjs <fixture.json> <lab_features.mjs>");
  process.exit(2);
}
const lf = await import(pathToFileURL(modulePath));
const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));

const TOL = 1e-6;
let failures = 0;

function fail(pos, msg) {
  failures++;
  console.error(`FAIL ${pos.id}: ${msg}`);
}

for (const pos of fixture.positions) {
  let facts;
  if (pos.mode === "sequence") {
    facts = lf.factsFromSequence(pos.moves);
  } else {
    facts = lf.factsFromFree(pos.stones.p0, pos.stones.p1, pos.to_move);
  }
  const sup = lf.buildSupport(facts.records.map(rec => [rec.q, rec.r]));

  // Support order must match the server exactly (features are node-indexed).
  const gotCoords = JSON.stringify(sup.coords);
  const wantCoords = JSON.stringify(pos.support.coords);
  if (gotCoords !== wantCoords) {
    fail(pos, `support coords differ\n  got  ${gotCoords}\n  want ${wantCoords}`);
    continue;
  }
  for (const seg of ["legalCount", "stoneCount", "haloCount"]) {
    const want = pos.support[seg.replace(/Count$/, "_count")];
    if (sup[seg] !== want) fail(pos, `${seg}: got ${sup[seg]}, want ${want}`);
  }
  if (facts.currentPlayer !== pos.to_move) {
    fail(pos, `to_move: got ${facts.currentPlayer}, want ${pos.to_move}`);
  }
  if (facts.phase !== pos.phase) {
    fail(pos, `phase: got ${facts.phase}, want ${pos.phase}`);
  }

  const planes = lf.buildFeatures(facts, sup);
  if (planes.length !== pos.planes.length) {
    fail(pos, `plane count: got ${planes.length}, want ${pos.planes.length}`);
    continue;
  }
  for (let f = 0; f < planes.length; f++) {
    const got = planes[f], want = pos.planes[f];
    if (got.length !== want.length) {
      fail(pos, `plane ${lf.FEATURE_NAMES[f]} length: got ${got.length}, want ${want.length}`);
      continue;
    }
    for (let i = 0; i < got.length; i++) {
      if (Math.abs(got[i] - want[i]) > TOL) {
        fail(
          pos,
          `plane ${lf.FEATURE_NAMES[f]} node ${i} (${sup.coords[i]}): ` +
          `got ${got[i]}, want ${want[i]}`,
        );
        break; // one mismatch per plane is enough signal
      }
    }
  }
}

if (failures > 0) {
  console.error(`${failures} parity failure(s) across ${fixture.positions.length} position(s)`);
  process.exit(1);
}
console.log(`ok: ${fixture.positions.length} positions, all planes match within ${TOL}`);
