"""The committed forcing-corpus preset data stays engine-true.

learn/data/forcing_corpus.json is generated by scripts/import_forcing_corpus.py
(which verifies at build time); this test keeps the COMMITTED artifact honest
against the engine so a hand edit or a stale regeneration cannot ship an
illegal preset. Engine-only — no torch, no solver.
"""

from __future__ import annotations

import json
from pathlib import Path

from showcase.lab_rules import validate_actions, validate_free_stones

import hexo_engine as engine
from hexo_engine.types import AxialCoord, PlacementAction

DATA = Path(__file__).resolve().parents[1] / "web" / "learn" / "data" / "forcing_corpus.json"


def _replay_terminal(cells) -> bool:
    state = engine.new_game()
    for i, (q, r) in enumerate(cells):
        action = PlacementAction(AxialCoord(q=int(q), r=int(r)))
        assert engine.is_legal_action(state, action), (i, q, r)
        result = engine.apply_action(state, action)
        assert not (result.terminal and i < len(cells) - 1), f"early terminal at {i}"
    return engine.terminal(state) is not None


def test_forcing_corpus_positions_are_engine_true():
    doc = json.loads(DATA.read_text(encoding="utf-8"))
    positions = doc["positions"]
    assert len(positions) == 19
    ids = [p["id"] for p in positions]
    assert len(set(ids)) == len(ids)
    titles = [p["title"] for p in positions]
    assert len(set(titles)) == len(titles), "dropdown titles must disambiguate"

    n_seq = n_free = n_line = 0
    for pos in positions:
        if "moves" in pos:
            n_seq += 1
            moves = [(int(q), int(r)) for q, r in pos["moves"]]
            # validate_actions is the endpoint's own gate: legal AND live.
            validate_actions(moves)
            if "line" in pos:
                n_line += 1
                full = moves + [(int(q), int(r)) for q, r in pos["line"]]
                assert _replay_terminal(full), f"{pos['id']}: line must end the game"
        else:
            n_free += 1
            free = pos["free"]
            p0 = [(int(q), int(r)) for q, r in free["p0"]]
            p1 = [(int(q), int(r)) for q, r in free["p1"]]
            validate_free_stones(p0, p1)
            assert free["to_move"] in (0, 1)
    assert (n_seq, n_line, n_free) == (17, 12, 2)
