/* mantis.js — shared library for the MantisNet "how it works" figures.
 *
 * Two halves:
 *
 * 1. JS transcriptions of the MantisNet builder's frozen vocabularies —
 *    the reversal-canonical ternary window patterns (377) and the orbit-48
 *    displacement classes (packages/mantisnet/python/mantisnet/builder.py).
 *    Every page that draws them first validates the transcription against
 *    data/mantis_walkthrough.json, which was generated by the real builder
 *    against the served checkpoint; a mismatch disables the figure rather
 *    than showing wrong classes.
 *
 * 2. SVG hex-board helpers on the same axial→pixel mapping as ../board.js,
 *    sized for inline figures.
 */

/* ---------- constants ---------- */

// Win axes in engine canonical order [Q, R, QR] (builder.AXES).
export const AXES = [[1, 0], [0, 1], [1, -1]];
export const AXIS_NAMES = ["Q", "R", "QR"];
export const WINDOW_LEN = 6;

// Stone colors (site palette) and the analysis-screen fill tints.
export const P0 = "#4f93ff", P1 = "#ff5650";
export const H0 = "#9fd0ff", H1 = "#ffb4aa";
// Q-value tick ramp endpoints (the live viewer's convention: blue = P0
// winning, red = P1 winning, grey = balanced).
const TICK_A = [127, 177, 255], TICK_B = [255, 135, 129], TICK_N = [154, 161, 169];

export const hexDist = (q, r) => Math.max(Math.abs(q), Math.abs(r), Math.abs(q + r));

/* ---------- ternary window patterns (builder.py §"Ternary tables") ----------
 * A window is a base-3 code over its six slots (digit at 3^k = slot k;
 * 0 empty, 1 own, 2 opponent, mover-relative). Reversal reverses the digit
 * string; the canonical form is the numeric minimum of the pair; ranks are
 * assigned over the ascending canonical codes of the 728 nonempty patterns
 * (377 orbits: 351 mirror pairs + 26 nonempty palindromes). */

const POW3 = [1, 3, 9, 27, 81, 243];

export const ternDigits = code => POW3.map(p => Math.floor(code / p) % 3);
export const ternCode = digits => digits.reduce((a, d, k) => a + d * POW3[k], 0);
export const ternReverse = code => ternCode(ternDigits(code).reverse());
export const ternCanon = code => Math.min(code, ternReverse(code));

const TERN_RANK = (() => {
  const canon = new Set();
  for (let p = 1; p < 729; p++) canon.add(ternCanon(p));
  const sorted = [...canon].sort((a, b) => a - b);
  const rank = new Map(sorted.map((c, i) => [c, i]));
  return code => rank.get(ternCanon(code));
})();
export const ternRank = TERN_RANK;
export const TERN_PATTERNS = 377;

/* ---------- orbit-48 displacement classes (builder.py orbit48_id) ----------
 * The orbit of an offset vector under the twelve board symmetries; ranks are
 * frozen by sorting representatives on (distance, canonical q, canonical r).
 */

const rot = ([q, r]) => [-r, q + r];
const ref = ([q, r]) => [r, q];

function canonDisplacement(q, r) {
  let best = null;
  for (const seed of [[q, r], ref([q, r])]) {
    let img = seed;
    for (let i = 0; i < 6; i++) {
      if (!best || img[0] < best[0] || (img[0] === best[0] && img[1] < best[1])) {
        best = [img[0], img[1]];
      }
      img = rot(img);
    }
  }
  return best;
}

const ORBIT_RANK = (() => {
  const reps = new Map();
  for (let q = -12; q <= 12; q++) {
    for (let r = -12; r <= 12; r++) {
      const d = hexDist(q, r);
      if (d < 1 || d > 12) continue;
      const [cq, cr] = canonDisplacement(q, r);
      reps.set(`${cq},${cr}`, [d, cq, cr]);
    }
  }
  const sorted = [...reps.values()].sort(
    (a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2]);
  const rank = new Map(sorted.map(([, q, r], i) => [`${q},${r}`, i]));
  return (dq, dr) => rank.get(canonDisplacement(dq, dr).join(","));
})();
export const orbit48 = ORBIT_RANK;
export const ORBIT48_CLASSES = 48;

/* ---------- data loading + self-check ---------- */

export async function fetchJSON(path) {
  const resp = await fetch(path, { cache: "no-cache" });
  if (!resp.ok) throw new Error(`${path}: HTTP ${resp.status}`);
  return resp.json();
}

/* Recompute every window's pattern rank and every focus radius edge's orbit
 * class from raw geometry and compare with what the real builder emitted.
 * Returns null if everything agrees, else a description of the first drift. */
export function selfCheck(wt) {
  for (const w of wt.windows) {
    if (TERN_RANK(ternCode(w.digits)) !== w.pattern) {
      return `window pattern drift at ${w.start} axis ${w.axis}`;
    }
  }
  const f = wt.focus;
  for (const e of f.radius_edges) {
    const got = ORBIT_RANK(e.stone[0] - f.q, e.stone[1] - f.r);
    if (got !== e.orbit) return `orbit drift at stone ${e.stone}`;
  }
  return null;
}

/* ---------- π′ (improve.py, the KLENT improvement operator) ----------
 * pi'(a) ∝ exp[(qScore_a + τ·ln prior_a) / (τ + λ)], normalized per position.
 * Computed in log space against the max for stability, like the real one. */
export function piPrime(priors, qScores, tau, lam) {
  const logits = priors.map(
    (p, i) => (qScores[i] + tau * Math.log(Math.max(p, 1e-30))) / (tau + lam));
  const m = Math.max(...logits);
  const exps = logits.map(x => Math.exp(x - m));
  const z = exps.reduce((a, b) => a + b, 0);
  return exps.map(x => x / z);
}

/* ---------- formatting ---------- */

export const fmtPct = p => p >= 0.9995 ? "100%"
  : p >= 0.10 ? (p * 100).toFixed(0) + "%"
  : p >= 0.01 ? (p * 100).toFixed(1) + "%"
  : p >= 0.0001 ? (p * 100).toFixed(2) + "%" : "<0.01%";
export const fmtV = v => (v >= 0 ? "+" : "") + v.toFixed(2);

export function qColor(v) {
  // v in [-1, 1], absolute frame: +1 = P0 (blue) winning.
  const t = Math.max(-1, Math.min(1, v));
  const mix = (a, b, k) => Math.round(a + (b - a) * k);
  const from = TICK_N, to = t >= 0 ? TICK_A : TICK_B, k = Math.abs(t);
  return `rgb(${mix(from[0], to[0], k)},${mix(from[1], to[1], k)},${mix(from[2], to[2], k)})`;
}

/* ---------- hex board figure ----------
 * Same mapping as ../board.js: pointy-top, x = S·√3·(q + r/2), y = 1.5·S·r.
 */

const NS = "http://www.w3.org/2000/svg";
const SQ3 = Math.sqrt(3);

export function el(tag, attrs, parent) {
  const node = document.createElementNS(NS, tag);
  for (const k in attrs) node.setAttribute(k, attrs[k]);
  if (parent) parent.appendChild(node);
  return node;
}

export function hexPts(cx, cy, rad) {
  const p = [];
  for (let i = 0; i < 6; i++) {
    const a = Math.PI / 180 * (60 * i - 30);
    p.push((cx + rad * Math.cos(a)).toFixed(2) + "," + (cy + rad * Math.sin(a)).toFixed(2));
  }
  return p.join(" ");
}

/* Build a static hex-board figure inside `svg` showing every cell in `cells`
 * (array of {q, r}) plus `stones` ({q, r, owner}). Returns a handle exposing
 * per-cell paint and mark helpers; all interaction is wired by the caller. */
export function hexBoard(svg, cells, stones, opts = {}) {
  const S = opts.size || 15;
  const DRAW = 0.94;
  const all = cells.concat(stones);
  const xs = all.map(c => S * SQ3 * (c.q + c.r / 2));
  const ys = all.map(c => S * 1.5 * c.r);
  const pad = S * 2;
  const x0 = Math.min(...xs) - pad, x1 = Math.max(...xs) + pad;
  const y0 = Math.min(...ys) - pad, y1 = Math.max(...ys) + pad;
  svg.setAttribute("viewBox", `${x0.toFixed(1)} ${y0.toFixed(1)} ${(x1 - x0).toFixed(1)} ${(y1 - y0).toFixed(1)}`);

  const tileG = el("g", {}, svg);
  const fillG = el("g", {}, svg);
  const stoneG = el("g", {}, svg);
  const markG = el("g", {}, svg);

  const X = (q, r) => S * SQ3 * (q + r / 2);
  const Y = r => S * 1.5 * r;
  const key = (q, r) => q + "," + r;

  const tiles = new Map();
  for (const c of cells) {
    const t = el("polygon", {
      points: hexPts(X(c.q, c.r), Y(c.r), S * DRAW),
      class: "mb-cell",
      "data-k": key(c.q, c.r),
    }, tileG);
    tiles.set(key(c.q, c.r), t);
  }

  const fills = new Map();
  for (const c of cells) {
    const f = el("polygon", {
      points: hexPts(X(c.q, c.r), Y(c.r), S * DRAW),
      class: "mb-fill",
      "fill-opacity": "0",
      "pointer-events": "none",
    }, fillG);
    fills.set(key(c.q, c.r), f);
  }

  for (const s of stones) {
    el("polygon", {
      points: hexPts(X(s.q, s.r), Y(s.r), S * DRAW),
      class: "mb-stone",
      fill: s.owner === 0 ? P0 : P1,
      "data-k": key(s.q, s.r),
    }, stoneG);
  }

  return {
    svg, S, X, Y, key, tiles, fills, markG,
    setFill(q, r, color, opacity) {
      const f = fills.get(key(q, r));
      if (!f) return;
      f.setAttribute("fill", color);
      f.setAttribute("fill-opacity", String(opacity));
    },
    clearFills() {
      for (const f of fills.values()) f.setAttribute("fill-opacity", "0");
    },
    setTileClass(q, r, cls, on) {
      const t = tiles.get(key(q, r));
      if (t) t.classList.toggle(cls, !!on);
    },
    clearTileClass(cls) {
      for (const t of tiles.values()) t.classList.remove(cls);
    },
    ring(q, r, cls) {
      return el("polygon", {
        points: hexPts(X(q, r), Y(r), S * 0.72),
        class: cls || "mb-ring",
      }, markG);
    },
    dot(q, r, color, rad) {
      return el("circle", {
        cx: X(q, r).toFixed(1), cy: Y(r).toFixed(1),
        r: String(rad || S * 0.22), fill: color,
        "pointer-events": "none",
      }, markG);
    },
    clearMarks() {
      while (markG.firstChild) markG.removeChild(markG.firstChild);
    },
  };
}

/* ---------- shared readout wiring ---------- */

export function readout(node) {
  const k = node.querySelector(".ro-k"), t = node.querySelector(".ro-t");
  const dk = k.textContent, dt = t.textContent;
  return {
    set(kk, tt) { k.textContent = kk; t.textContent = tt; },
    reset() { k.textContent = dk; t.textContent = dt; },
  };
}
